# It prepares a Maven release, creates a release branch, performs the release, and bumps the version.
name: (WF) Maven Release

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'
        description: 'Java version to use for the job'
      java-distribution:
        required: false
        type: string
        default: 'temurin'
        description: 'Java distribution to use for the job'
      maven-settings-xml-server-id:
        required: false
        type: string
        default: 'central'
        description: 'Used to generate server ID in generated maven settings XML to upload artifacts'
      maven-cmd-customization:
        required: false
        type: string
        default: ''
        description: 'Customize Maven command for release commands'

# Prerequisites for variables:
# Set secrets in the repository or organization settings:
# - TECHUSER_GPG_KEY_ID: GPG key ID for git commands
# - TECHUSER_GPG_PRIVATE_KEY: GPG private key for signing commits
# - TECHUSER_GPG_KEY_PASSPHRASE: GPG key passphrase
# - TECHUSER_SSH_PRIVATE_KEY: SSH private key for git commands
# - TECHUSER_USERNAME: Git username for git commands
# - TECHUSER_EMAIL: Git email for git commands
# - TECHUSER_GH_TOKEN: GitHub token for GitHub API commands
# - MAVEN_CENTRAL_USER_USERNAME: Maven Central username for publishing artifacts
# - MAVEN_CENTRAL_USER_PASSWORD: Maven Central password for publishing artifacts
jobs:
  deploy-snapshot:

    runs-on: ubuntu-latest

    steps:
      - name: Print
        shell: bash
        run: |
          echo "github.event.inputs.comment: '${{ github.event.inputs.comment }}'"
          echo "github.ref_name: '${{ github.ref_name }}'"
          echo "github.event.ref: '${{ github.event.ref }}'"
          echo "github.repository: '${{ github.repository }}'"
          echo "github.workspace: '${{ github.workspace }}'"
          echo "java-version: '${{ inputs.java-version }}'"
          echo "java-distribution: '${{ inputs.java-distribution }}'"
          echo "maven-settings-xml-server-id: '${{ inputs.maven-settings-xml-server-id }}'"
          echo "maven-cmd-customization: '${{ inputs.maven-cmd-customization }}'"
          echo "secrets.TECHUSER_GPG_KEY_ID: '${{ secrets.TECHUSER_GPG_KEY_ID }}'"
          echo "secrets.TECHUSER_GPG_PRIVATE_KEY: '${{ secrets.TECHUSER_GPG_PRIVATE_KEY }}'"
          echo "secrets.TECHUSER_GPG_KEY_PASSPHRASE: '${{ secrets.TECHUSER_GPG_KEY_PASSPHRASE }}'"
          echo "secrets.TECHUSER_SSH_PRIVATE_KEY: '${{ secrets.TECHUSER_SSH_PRIVATE_KEY }}'"
          echo "secrets.TECHUSER_USERNAME: '${{ secrets.TECHUSER_USERNAME }}'"
          echo "secrets.TECHUSER_EMAIL: '${{ secrets.TECHUSER_EMAIL }}'"
          echo "secrets.TECHUSER_GH_TOKEN: '${{ secrets.TECHUSER_GH_TOKEN }}'"
          echo "secrets.MAVEN_CENTRAL_USER_USERNAME: '${{ secrets.MAVEN_CENTRAL_USER_USERNAME }}'"
          echo "secrets.MAVEN_CENTRAL_USER_PASSWORD: '${{ secrets.MAVEN_CENTRAL_USER_PASSWORD }}'"

      - name: Check branch (workflow can run only main/master branch)
        id: precheck
        shell: bash
        run: |
          if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref_name }}" == "master" ]]; then
            echo "🚀 Start ${{ github.ref_name }} release..."
            VERSION_TYPE=MINOR
            echo "VERSION_TYPE=${VERSION_TYPE}" 
            echo "VERSION_TYPE=${VERSION_TYPE}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == release/* ]]; then
            echo "🚀 Start ${{ github.ref_name }} release..."
            VERSION_TYPE=BUGFIX
            echo "VERSION_TYPE=${VERSION_TYPE}" 
            echo "VERSION_TYPE=${VERSION_TYPE}" >> $GITHUB_OUTPUT
          else 
            echo "⛔ workflow can only be run on the main/master branch!"
            exit 1
          fi

    #   - name: Import GPG key
    #     shell: bash
    #     # GPG private key, which is exported with armor (start with: '-----BEGIN PGP PRIVATE KEY BLOCK-----') and it is encoded with base64, and stored in secrets
    #     # the private key is decoded with base64 and it is imported
    #     # run: echo "${{ secrets.TECHUSER_GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import
    #     # GPG private key, which is exported with armor (start with: '-----BEGIN PGP PRIVATE KEY BLOCK-----') and stored in secrets
    #     run: echo "${{ secrets.TECHUSER_GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          # Private SSH key in PEM format (start with: '-----BEGIN RSA PRIVATE KEY-----')
          key: ${{ secrets.TECHUSER_SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: unnecessary


      - name: Set up JDK version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          server-id: ${{ inputs.maven-settings-xml-server-id }}
          # Environment variable name for the username for authentication to the Apache Maven repository. Default is GITHUB_ACTOR.
          server-username: MAVEN_USERNAME
          # Environment variable name for password or token for authentication to the Apache Maven repository. Default is GITHUB_TOKEN.
          server-password: MAVEN_PASSWORD
          #   settings-path: ${{ github.workspace }} # location for the settings.xml file
          gpg-private-key: ${{ secrets.TECHUSER_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'

      - name: Configure GIT for signed commit
        shell: bash
        run: |
          git config --global user.name "${{ secrets.TECHUSER_USERNAME }}"
          git config --global user.email "${{ secrets.TECHUSER_EMAIL }}"
          git config --global user.signingkey "${{ secrets.TECHUSER_GPG_KEY_ID }}"
          git config --global commit.gpgsign true
          git config --global tag.gpgSign true

      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TECHUSER_GH_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Maven release prepare DryRun and release branch
        id: prepare
        shell: bash
        run: |
          mvn -B ${{ inputs.maven-cmd-customization }} release:prepare -DdryRun=true
          if [[ "${{ steps.precheck.outputs.VERSION_TYPE }}" == "MINOR" ]]; then
            SCM_TAG=`cat release.properties | grep -w "scm.tag" | cut -d'=' -f2`
            echo "SCM_TAG=${SCM_TAG}" 
            echo "SCM_TAG=${SCM_TAG}" >> $GITHUB_OUTPUT
          fi
          mvn -B ${{ inputs.maven-cmd-customization }} release:clean --file pom.xml
          if [[ "${{ steps.precheck.outputs.VERSION_TYPE }}" == "MINOR" ]]; then
            RELEASE_BRANCH_NAME=release/${SCM_TAG%.*}.x
            echo "RELEASE_BRANCH_NAME=${RELEASE_BRANCH_NAME}"
            echo "RELEASE_BRANCH_NAME=${RELEASE_BRANCH_NAME}" >> $GITHUB_OUTPUT
            echo new release branch name is ${RELEASE_BRANCH_NAME}
            MR_BRANCH_NAME=feature/${SCM_TAG}-release
            echo "MR_BRANCH_NAME=${MR_BRANCH_NAME}"
            echo "MR_BRANCH_NAME=${MR_BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Create release branch
        id: createreleasebranch
        if: ${{ steps.precheck.outputs.VERSION_TYPE == 'MINOR' }}
        shell: bash
        run: |
          git checkout -b ${{ steps.prepare.outputs.RELEASE_BRANCH_NAME }} refs/remotes/origin/${{ github.ref_name }}
          git push --set-upstream origin ${{ steps.prepare.outputs.RELEASE_BRANCH_NAME }}
          echo "${{ steps.prepare.outputs.RELEASE_BRANCH_NAME }} branch created."

      - name: Checkout release branch
        if: ${{ steps.precheck.outputs.VERSION_TYPE == 'MINOR' }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TECHUSER_GH_TOKEN }}
          ref: ${{ steps.prepare.outputs.RELEASE_BRANCH_NAME }}

      - name: Maven release PREPARE
        shell: bash
        run: |
            mvn -B ${{ inputs.maven-cmd-customization }} release:prepare -Dgpg.keyname=${{ secrets.TECHUSER_GPG_KEY_ID }}
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.TECHUSER_GPG_KEY_PASSPHRASE }}

      - name: Maven release PERFORM
        shell: bash
        run: mvn -B ${{ inputs.maven-cmd-customization }} release:perform -Dgpg.keyname=${{ secrets.TECHUSER_GPG_KEY_ID }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER_USERNAME }}
          MAVEN_PASSWORD: '${{ secrets.MAVEN_CENTRAL_USER_PASSWORD }}'
          MAVEN_GPG_PASSPHRASE: ${{ secrets.TECHUSER_GPG_KEY_PASSPHRASE }}

      - name: Checkout main/master
        if: ${{ steps.precheck.outputs.VERSION_TYPE == 'MINOR' }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TECHUSER_GH_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Create bump version branch
        if: ${{ steps.precheck.outputs.VERSION_TYPE == 'MINOR' }}
        id: createBumpBranch
        shell: bash
        run: |
          git checkout -b ${{ steps.prepare.outputs.MR_BRANCH_NAME }} refs/remotes/origin/${{ github.ref_name }}
          git push --set-upstream origin ${{ steps.prepare.outputs.MR_BRANCH_NAME }}
          echo "${{ steps.prepare.outputs.MR_BRANCH_NAME }} branch created."

      - name: Checkout bump version branch
        if: ${{ steps.precheck.outputs.VERSION_TYPE == 'MINOR' }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TECHUSER_GH_TOKEN }}
          ref: ${{ steps.prepare.outputs.MR_BRANCH_NAME }}

      - name: Create bump MINOR version branch
        if: ${{ steps.precheck.outputs.VERSION_TYPE == 'MINOR' }}
        id: bumpbranch
        shell: bash
        run: |
          NEXT_MASTER_VERSION=$(echo  ${{ steps.prepare.outputs.SCM_TAG }} |  awk -F'.' '{print $1"."$2+1"."0}' |  sed s/[.]$//)
          TARGET_BRANCH_NEXT_VERSION=$(echo $NEXT_MASTER_VERSION | rev | cut -d '-' -f1 | rev)-SNAPSHOT
           mvn -B release:update-versions -DdevelopmentVersion=$TARGET_BRANCH_NEXT_VERSION
          COMMIT_MESSAGE="Bump version to $TARGET_BRANCH_NEXT_VERSION"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          git add .
          git commit -a -m "$COMMIT_MESSAGE"
          git push --atomic origin ${{ steps.prepare.outputs.MR_BRANCH_NAME }}
          echo next version on ${{ github.ref_name }} is $TARGET_BRANCH_NEXT_VERSION

      # This step creates a pull request between the current branch and the base branch.
      - name: Create Pull Request
        if: ${{ steps.precheck.outputs.VERSION_TYPE == 'MINOR' }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.TECHUSER_GH_TOKEN }}
        run: |
          gh pr create --base ${{ github.ref_name }} --fill-verbose --title '${{steps.bumpbranch.outputs.COMMIT_MESSAGE}}'